version: "1"
rules:                      # Array of rules
  - base: staging            # Required. Target branch
    upstream: memcached:staging    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: next
    upstream: memcached:next        # Required. Can be a branch in the same forked repo.
    mergeMethod: hardreset